spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_first_base
    username: Boss
    password: 2309
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
car:
  maxCars: 4
  sorting:
    - id
    - carBrand
    - price
    - licensePlate
loan:
  minIncome: 40000
  minPriseCar: 1000000